# ESAT Workflow — GPU Accelerated

This notebook follows the official EPA ESAT workflow with GPU-accelerated training. Changes:
- `use_gpu=True, parallel=False` on BatchSA, Bootstrap, DISP, BS-DISP
- GPU batched multi-model training (`ls_nmf_batched`)
- Delta-optimised DISP binary search
- Backend metadata recorded

### Imports

In [1]:
import os, sys, json, warnings, logging
warnings.filterwarnings("ignore"); logging.disable(logging.CRITICAL)
sys.path.insert(0, os.path.abspath(".."))
from esat.data.datahandler import DataHandler
from esat.model.sa import SA
from esat.model.batch_sa import BatchSA
from esat.data.analysis import ModelAnalysis, BatchAnalysis

### Dataset Paths

In [2]:
cwd = os.getcwd()
data_dir = os.path.join(cwd, "..", "data")
br_input_file = os.path.join(data_dir, "Dataset-BatonRouge-con.csv")
br_uncertainty_file = os.path.join(data_dir, "Dataset-BatonRouge-unc.csv")
br_output_path = os.path.join(data_dir, "output", "BatonRouge")
b_input_file = os.path.join(data_dir, "Dataset-Baltimore_con.txt")
b_uncertainty_file = os.path.join(data_dir, "Dataset-Baltimore_unc.txt")
b_output_path = os.path.join(data_dir, "output", "Baltimore")
sl_input_file = os.path.join(data_dir, "Dataset-StLouis-con.csv")
sl_uncertainty_file = os.path.join(data_dir, "Dataset-StLouis-unc.csv")
sl_output_path = os.path.join(data_dir, "output", "StLouis")

### Input Parameters

In [3]:
index_col = "Date"
factors = 6
method = "ls-nmf"
models = 20
init_method = "col_means"
init_norm = True
seed = 42
max_iterations = 20000
converge_delta = 0.01
converge_n = 50
verbose = True
use_gpu = True
parallel = False

### Dataset Selection

In [4]:
input_file = br_input_file
uncertainty_file = br_uncertainty_file
output_path = br_output_path

### Load Data

In [5]:
data_handler = DataHandler(input_path=input_file, uncertainty_path=uncertainty_file, index_col=index_col)
V, U = data_handler.get_data()
print("V=%s  (%d features, %d samples)" % (V.shape, len(data_handler.features), V.shape[0]))

V=(307, 41)  (41 features, 307 samples)

### Data Metrics

In [6]:
data_handler.metrics

,Category,S/N,Min,25th,50th,75th,Max
124-Trimethylbenzene,strong,5.445168,0.005000,0.820001,1.290001,1.865001,5.470003
224-Trimethylpentane,strong,5.666667,0.410000,1.580001,2.490002,3.865002,13.560008
234-Trimethylpentane,strong,5.537459,0.005000,0.530000,0.820001,1.300001,4.410003
23-Dimethylbutane,strong,5.500543,0.005000,0.640000,1.110001,2.285001,10.500007
23-Dimethylpentane,strong,5.463626,0.005000,0.340000,0.490000,0.780000,3.310002
2-Methylheptane,strong,5.039088,0.005000,0.215000,0.330000,0.535000,2.480002
3-Methylhexane,strong,5.648208,0.005000,0.655000,1.050001,1.510001,7.780005
3-Methylpentane,strong,5.611292,0.540000,1.720001,2.990002,5.945004,29.100018
Acetylene,strong,5.666667,0.380000,1.410001,1.990001,2.835002,8.070005
Benzene,strong,5.666667,0.590000,1.960001,2.770002,4.440003,9.330006
Cis-2-Butene,strong,3.100977,0.005000,0.005000,0.120000,0.310000,21.510013
Cis-2-Pentene,strong,5.057546,0.005000,0.220000,0.370000,0.720000,19.130012
Ethane,strong,5.666667,2.570002,8.285005,12.070008,17.890011,49.970031
Ethylbenzene,strong,5.666667,0.200000,0.620000,0.940001,1.450001,3.760002
Ethylene,strong,5.666667,0.890001,3.055002,5.260003,10.370006,49.490031
Isobutane,strong,5.666667,0.690000,2.705002,4.680003,7.700005,36.330023
Isopentane,strong,5.666667,2.500002,6.530004,10.260006,16.080010,125.500079
Isoprene,strong,5.555917,0.005000,0.890001,2.520002,4.840003,9.420006
Isopropylbenzene,strong,2.067318,0.005000,0.005000,0.005000,0.220000,6.640004
M_P Xylene,strong,5.666667,0.470000,1.845001,2.950002,4.510003,13.050008
M-Diethylbenzene,strong,2.436482,0.005000,0.005000,0.005000,0.230000,1.740001
M-Ethyltoluene,strong,5.519001,0.005000,0.530000,0.890001,1.395001,4.670003
N-Butane,strong,5.666667,1.650001,4.790003,7.360005,11.445007,56.230035
N-Decane,strong,5.168295,0.005000,0.280000,0.430000,0.690000,1.760001
N-Heptane,strong,5.666667,0.210000,0.730000,1.060001,1.515001,5.350003
N-Hexane,strong,5.611292,0.660000,2.170001,4.530003,9.820006,92.560058
N-Nonane,strong,5.408252,0.005000,0.310000,0.460000,0.670000,1.950001
N-Octane,strong,5.574376,0.005000,0.405000,0.630000,0.890001,3.100002
N-Pentane,strong,5.666667,0.710000,3.770002,5.450003,9.270006,38.580024
N-Propylbenzene,strong,3.617807,0.005000,0.005000,0.220000,0.330000,0.940001
N-Undecane,strong,4.983713,0.005000,0.250000,0.370000,0.550000,2.860002
O-Ethyltoluene,strong,4.946797,0.005000,0.240000,0.390000,0.585000,1.620001
O-Xylene,strong,5.666667,0.220000,0.800001,1.160001,1.735001,5.290003
Propane,strong,5.666667,2.260001,8.250005,12.270008,18.440012,70.960044
Propylene,strong,5.666667,0.380000,1.285001,2.450002,4.705003,24.900016
Styrene,strong,4.891422,0.005000,0.270000,0.500000,0.885001,7.650005
Toluene,strong,5.666667,1.310001,3.890002,5.950004,8.690005,26.870017
Trans-2-Butene,strong,2.971770,0.005000,0.005000,0.090000,0.300000,3.210002
Trans-2-Pentene,strong,5.408252,0.005000,0.405000,0.700000,1.300001,17.280011
Unidentified,strong,1.000000,1.020135,28.923549,50.394956,76.587424,385.184875
TNMOC,strong,0.000000,44.420000,113.616462,158.820000,249.795150,708.467700

In [7]:
# data_handler.set_category(feature="Unidentified", category="bad")
data_handler.metrics

,Category,S/N,Min,25th,50th,75th,Max
124-Trimethylbenzene,strong,5.445168,0.005000,0.820001,1.290001,1.865001,5.470003
224-Trimethylpentane,strong,5.666667,0.410000,1.580001,2.490002,3.865002,13.560008
234-Trimethylpentane,strong,5.537459,0.005000,0.530000,0.820001,1.300001,4.410003
23-Dimethylbutane,strong,5.500543,0.005000,0.640000,1.110001,2.285001,10.500007
23-Dimethylpentane,strong,5.463626,0.005000,0.340000,0.490000,0.780000,3.310002
2-Methylheptane,strong,5.039088,0.005000,0.215000,0.330000,0.535000,2.480002
3-Methylhexane,strong,5.648208,0.005000,0.655000,1.050001,1.510001,7.780005
3-Methylpentane,strong,5.611292,0.540000,1.720001,2.990002,5.945004,29.100018
Acetylene,strong,5.666667,0.380000,1.410001,1.990001,2.835002,8.070005
Benzene,strong,5.666667,0.590000,1.960001,2.770002,4.440003,9.330006
Cis-2-Butene,strong,3.100977,0.005000,0.005000,0.120000,0.310000,21.510013
Cis-2-Pentene,strong,5.057546,0.005000,0.220000,0.370000,0.720000,19.130012
Ethane,strong,5.666667,2.570002,8.285005,12.070008,17.890011,49.970031
Ethylbenzene,strong,5.666667,0.200000,0.620000,0.940001,1.450001,3.760002
Ethylene,strong,5.666667,0.890001,3.055002,5.260003,10.370006,49.490031
Isobutane,strong,5.666667,0.690000,2.705002,4.680003,7.700005,36.330023
Isopentane,strong,5.666667,2.500002,6.530004,10.260006,16.080010,125.500079
Isoprene,strong,5.555917,0.005000,0.890001,2.520002,4.840003,9.420006
Isopropylbenzene,strong,2.067318,0.005000,0.005000,0.005000,0.220000,6.640004
M_P Xylene,strong,5.666667,0.470000,1.845001,2.950002,4.510003,13.050008
M-Diethylbenzene,strong,2.436482,0.005000,0.005000,0.005000,0.230000,1.740001
M-Ethyltoluene,strong,5.519001,0.005000,0.530000,0.890001,1.395001,4.670003
N-Butane,strong,5.666667,1.650001,4.790003,7.360005,11.445007,56.230035
N-Decane,strong,5.168295,0.005000,0.280000,0.430000,0.690000,1.760001
N-Heptane,strong,5.666667,0.210000,0.730000,1.060001,1.515001,5.350003
N-Hexane,strong,5.611292,0.660000,2.170001,4.530003,9.820006,92.560058
N-Nonane,strong,5.408252,0.005000,0.310000,0.460000,0.670000,1.950001
N-Octane,strong,5.574376,0.005000,0.405000,0.630000,0.890001,3.100002
N-Pentane,strong,5.666667,0.710000,3.770002,5.450003,9.270006,38.580024
N-Propylbenzene,strong,3.617807,0.005000,0.005000,0.220000,0.330000,0.940001
N-Undecane,strong,4.983713,0.005000,0.250000,0.370000,0.550000,2.860002
O-Ethyltoluene,strong,4.946797,0.005000,0.240000,0.390000,0.585000,1.620001
O-Xylene,strong,5.666667,0.220000,0.800001,1.160001,1.735001,5.290003
Propane,strong,5.666667,2.260001,8.250005,12.270008,18.440012,70.960044
Propylene,strong,5.666667,0.380000,1.285001,2.450002,4.705003,24.900016
Styrene,strong,4.891422,0.005000,0.270000,0.500000,0.885001,7.650005
Toluene,strong,5.666667,1.310001,3.890002,5.950004,8.690005,26.870017
Trans-2-Butene,strong,2.971770,0.005000,0.005000,0.090000,0.300000,3.210002
Trans-2-Pentene,strong,5.408252,0.005000,0.405000,0.700000,1.300001,17.280011
Unidentified,strong,1.000000,1.020135,28.923549,50.394956,76.587424,385.184875
TNMOC,strong,0.000000,44.420000,113.616462,158.820000,249.795150,708.467700

In [8]:
data_handler.plot_data_uncertainty(feature_idx=0, include_menu=False)

In [9]:
data_handler.plot_feature_data(x_idx=0, y_idx=1)

In [10]:
data_handler.plot_feature_timeseries(feature_selection=[0])

In [11]:
# data_handler.plot_2d_histogram(x_col="124-Trimethylbenzene", y_col="224-Trimethylpentane")

### Train Model (GPU)

In [12]:
%%capture
sa_models = BatchSA(V=V, U=U, factors=factors, models=models, method=method, seed=seed,
                    max_iter=max_iterations, init_method=init_method, init_norm=init_norm,
                    converge_delta=converge_delta, converge_n=converge_n,
                    verbose=verbose, use_gpu=use_gpu, parallel=parallel)
_ = sa_models.train()

[esat_rust] Metal device initialized successfully

In [13]:
best_model = sa_models.best_model
sa_model = sa_models.results[best_model]
print("Best model: %d, Q(true)=%.1f" % (best_model+1, sa_model.Qtrue))

Best model: 17, Q(true)=64616.6

### Save / Load (optional)

In [14]:
# batch_name = "test_batch_01"
# batch_output_dir = os.path.join(os.getcwd(), "test_batch")
# os.mkdir(batch_output_dir)
# header = data_handler.features
# sa_models.save(batch_name=batch_name, output_directory=batch_output_dir, pickle_model=True, pickle_batch=True, header=header)

In [15]:
# saved_batch_file = os.path.join(os.getcwd(), "test_batch", "test_batch_01.pkl")
# batch_sa2 = BatchSA.load(file_path=saved_batch_file)

### Post-Training Analysis

In [16]:
batch_analysis = BatchAnalysis(batch_sa=sa_models, data_handler=data_handler)
plot_test = batch_analysis.plot_loss(show=False)
plot_test

In [17]:
batch_analysis.plot_loss_distribution()

In [18]:
batch_analysis.plot_temporal_residuals(feature_idx=2)

In [19]:
batch_analysis.aggregated_output[0]

,124-Trimethylbenzene,224-Trimethylpentane,234-Trimethylpentane,23-Dimethylbutane,23-Dimethylpentane,2-Methylheptane,3-Methylhexane,3-Methylpentane,Acetylene,Benzene,...,O-Ethyltoluene,O-Xylene,Propane,Propylene,Styrene,Toluene,Trans-2-Butene,Trans-2-Pentene,Unidentified,TNMOC
0,0.184512,1.244582,0.379653,0.622446,0.284144,0.148353,0.705168,1.687358,1.053434,1.719147,...,0.043490,0.616470,8.687680,1.155071,0.006344,3.088368,0.010496,0.348974,6.446665,107.137138
1,2.428840,4.077993,1.543661,2.095303,0.834247,0.596980,1.202579,4.589378,2.908373,3.859955,...,0.736471,1.870334,14.736505,4.240337,1.130519,9.176787,0.369185,1.401220,25.717904,231.325717
2,1.353336,3.105354,1.039671,2.012180,0.648008,0.382346,1.176027,4.914517,2.110875,3.247630,...,0.372512,1.251990,16.151322,3.485749,0.560693,6.523628,0.309146,1.549927,25.080579,234.621531
3,5.205173,6.249464,2.223050,1.332309,0.989485,0.679815,0.901331,4.177775,5.568485,6.624315,...,1.533585,3.276769,17.880854,5.248813,1.827397,16.211806,0.259283,1.246385,62.118581,285.463509
4,1.397920,2.720126,0.875267,0.891619,0.510252,0.365848,0.838304,2.688790,2.402423,3.588934,...,0.443973,1.489025,13.782626,2.324397,0.552958,7.587694,0.009539,0.661668,9.227086,171.709308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,0.302810,2.196949,0.554277,3.074965,0.580090,0.317097,1.204388,7.400673,0.620474,2.217390,...,0.068692,0.429836,17.549136,2.788346,0.284045,3.490221,0.327249,3.113312,8.817008,253.417619
303,0.204440,1.120506,0.261071,1.290885,0.275190,0.133244,0.597772,3.314934,0.510766,1.320519,...,0.044409,0.303849,8.973082,1.180065,0.075986,2.150488,0.093992,1.382011,6.327609,124.498087
304,0.129159,0.491204,0.063170,0.156075,0.049241,0.018508,0.121835,0.954504,0.509666,1.007739,...,0.032071,0.241034,5.222628,0.618414,0.018092,1.502960,0.002893,0.201984,3.398815,56.357284
305,0.812346,1.436844,0.368046,0.501876,0.234623,0.058646,0.464564,1.942067,1.320871,1.884089,...,0.189255,0.647854,8.242635,1.091182,0.055622,3.529034,0.009302,0.670218,22.681847,114.424270
306,1.764823,4.353482,1.722941,2.853131,1.074191,0.775671,1.919183,5.525027,2.788613,4.019587,...,0.572783,1.983502,17.702578,4.427578,1.022097,9.490874,0.358661,1.686103,10.760800,267.177797

In [20]:
model_analysis = ModelAnalysis(datahandler=data_handler, model=sa_model, selected_model=best_model)

In [21]:
abs_threshold = 3.0
threshold_residuals = model_analysis.plot_residual_histogram(feature_idx=0, abs_threshold=abs_threshold)

In [22]:
model_analysis.features_metrics()

,Feature,Input Mean,Input Var,Est Mean,Est Var,RMSE
0,124-Trimethylbenzene,1.4470,0.8667,1.1547,0.4850,0.8246
1,224-Trimethylpentane,3.0720,4.7755,2.6794,2.4659,1.3679
2,234-Trimethylpentane,1.0331,0.5468,0.8692,0.3339,0.5257
3,23-Dimethylbutane,1.8203,3.0425,1.3683,2.2522,1.5916
4,23-Dimethylpentane,0.6146,0.1861,0.5513,0.1347,0.2701
5,2-Methylheptane,0.3946,0.0888,0.3233,0.0708,0.2636
6,3-Methylhexane,1.2048,0.6763,1.0007,0.4245,0.6107
7,3-Methylpentane,4.8781,21.8641,3.4068,8.1883,4.4258
8,Acetylene,2.3288,1.7813,2.0843,1.2853,0.8496
9,Benzene,3.3562,3.5024,3.0388,2.2684,1.1898
10,Cis-2-Butene,0.5120,3.3329,0.1603,0.0573,2.3042
11,Cis-2-Pentene,0.7407,1.9878,0.5530,0.4074,1.3191
12,Ethane,13.8858,54.8394,11.9438,32.2129,6.9695
13,Ethylbenzene,1.1182,0.4504,1.0264,0.3512,0.3778
14,Ethylene,8.0605,55.5571,5.1058,7.6244,8.2596
15,Isobutane,6.5486,37.4585,4.9111,9.6603,5.6127
16,Isopentane,16.4019,335.2777,13.3448,118.1641,12.4490
17,Isoprene,3.0620,5.6677,2.3610,4.1410,1.9784
18,Isopropylbenzene,0.1944,0.2698,0.0157,0.0001,0.6844
19,M_P Xylene,3.4735,4.7138,3.1169,3.7470,1.0612
20,M-Diethylbenzene,0.1431,0.0529,0.0263,0.0004,0.3084
21,M-Ethyltoluene,1.1111,0.6886,0.9200,0.4984,0.5830
22,N-Butane,10.6112,89.6478,9.1598,47.4076,5.4549
23,N-Decane,0.5090,0.1148,0.4249,0.0912,0.2705
24,N-Heptane,1.2217,0.5050,1.1434,0.3844,0.4166
25,N-Hexane,8.5370,131.2640,4.4166,13.6975,13.1262
26,N-Nonane,0.5280,0.1072,0.4505,0.0792,0.2811
27,N-Octane,0.7170,0.1913,0.6179,0.1393,0.3707
28,N-Pentane,7.7731,43.4393,6.6879,23.3816,4.1174
29,N-Propylbenzene,0.2143,0.0402,0.1893,0.0408,0.1019
30,N-Undecane,0.4328,0.1057,0.3561,0.0628,0.2708
31,O-Ethyltoluene,0.4329,0.0940,0.3754,0.0938,0.1921
32,O-Xylene,1.3785,0.7025,1.2471,0.5210,0.4602
33,Propane,15.7796,136.8430,13.2931,57.0426,9.8710
34,Propylene,4.0061,19.0418,2.5021,2.8237,4.7645
35,Styrene,0.6460,0.4521,0.3845,0.1571,0.7419
36,Toluene,6.9727,18.3469,6.3634,12.3228,2.3511
37,Trans-2-Butene,0.2614,0.2447,0.1529,0.0534,0.5026
38,Trans-2-Pentene,1.2762,3.7176,0.9908,1.2397,1.4204
39,Unidentified,63.2019,3039.9197,16.7040,143.8984,89.6589
40,TNMOC,199.9007,14712.0781,185.7153,11683.0675,65.8564

In [23]:
model_analysis.calculate_statistics()
model_analysis.statistics

,Features,Category,r2,Intercept,Intercept SE,Slope,Slope SE,SE,SE Regression,Anderson Normal Residual,Anderson Statistic,Shapiro Normal Residuals,Shapiro PValue,KS Normal Residuals,KS PValue,KS Statistic
0,124-Trimethylbenzene,strong,0.598333,0.317437,0.046709,0.578633,0.027147,0.033701,0.441359,15.0,0.461426,Yes,1.103956e-01,Yes,8.920712e-01,0.032463
1,224-Trimethylpentane,strong,0.816320,0.684955,0.066482,0.649245,0.017634,0.058216,0.673009,15.0,0.221996,Yes,6.926874e-01,Yes,9.566740e-01,0.028629
2,234-Trimethylpentane,strong,0.731947,0.178530,0.029433,0.668553,0.023166,0.022073,0.299169,No,2.090344,No,1.781553e-04,Yes,1.434398e-01,0.064957
3,23-Dimethylbutane,strong,0.549750,0.207063,0.083341,0.637934,0.033057,0.067841,1.007012,No,1.181866,No,1.201227e-03,Yes,3.157259e-01,0.054235
4,23-Dimethylpentane,strong,0.772010,0.091947,0.017464,0.747441,0.023258,0.011776,0.175218,No,4.083753,No,1.925900e-08,No,3.872562e-02,0.079581
5,2-Methylheptane,strong,0.575684,0.056041,0.016467,0.677397,0.033300,0.011314,0.173348,No,1.562348,No,2.551971e-04,Yes,3.340349e-01,0.053380
6,3-Methylhexane,strong,0.712165,0.195256,0.035500,0.668549,0.024337,0.025298,0.349540,No,3.921630,No,5.821765e-10,No,6.759968e-03,0.095660
7,3-Methylpentane,strong,0.542567,1.207845,0.160146,0.450774,0.023700,0.183531,1.935357,No,1.422894,No,1.430768e-03,Yes,4.315883e-01,0.049270
8,Acetylene,strong,0.775823,0.341907,0.061813,0.748185,0.023029,0.036145,0.536773,15.0,0.221399,Yes,6.802330e-01,Yes,7.453241e-01,0.038244
9,Benzene,strong,0.776537,0.658662,0.083708,0.709186,0.021784,0.051147,0.711972,10.0,0.581265,Yes,2.174830e-01,Yes,6.621632e-01,0.041091
10,Cis-2-Butene,strong,0.020225,0.150729,0.014097,0.018655,0.007435,0.103141,0.237044,No,18.666245,No,3.043210e-17,No,1.371759e-12,0.212027
11,Cis-2-Pentene,strong,0.537521,0.307163,0.028076,0.331914,0.017629,0.059192,0.434068,No,2.548643,No,1.121374e-05,No,4.486705e-02,0.078074
12,Ethane,strong,0.506284,4.371344,0.485268,0.545338,0.030836,0.297877,3.987984,15.0,0.311690,Yes,3.390879e-01,Yes,9.309442e-01,0.030393
13,Ethylbenzene,strong,0.816822,0.133860,0.028224,0.798122,0.021642,0.016412,0.253644,15.0,0.376775,Yes,5.408777e-01,Yes,5.516711e-01,0.044864
14,Ethylene,strong,0.474589,3.048713,0.168803,0.255207,0.015376,0.336800,2.001490,2.5,0.802546,No,9.092162e-03,Yes,3.753506e-01,0.051558
15,Isobutane,strong,0.608939,2.315930,0.162992,0.396284,0.018184,0.238278,1.943646,15.0,0.555102,Yes,3.974440e-01,Yes,8.219749e-01,0.035442
16,Isopentane,strong,0.835377,4.445105,0.339048,0.542602,0.013792,0.540228,4.410496,No,1.820650,No,8.382260e-04,No,4.658073e-02,0.077686
17,Isoprene,strong,0.648260,0.253728,0.112587,0.688220,0.029028,0.080865,1.206886,No,4.182781,No,7.792427e-07,No,2.399246e-03,0.104031
18,Isopropylbenzene,strong,0.057651,0.014632,0.000691,0.005379,0.001245,0.029495,0.011297,No,27.028694,No,1.235548e-18,No,5.980576e-22,0.281099
19,M_P Xylene,strong,0.876462,0.217586,0.073501,0.834684,0.017943,0.043903,0.680366,No,3.809177,No,3.525663e-13,No,3.996770e-02,0.079261
20,M-Diethylbenzene,strong,0.420989,0.017738,0.001088,0.059814,0.004017,0.012380,0.016139,No,18.345935,No,9.795317e-16,No,2.761726e-12,0.209382
21,M-Ethyltoluene,strong,0.737926,0.107994,0.034585,0.730859,0.024940,0.024248,0.361417,No,1.968576,No,5.309823e-05,Yes,9.441846e-02,0.069961
22,N-Butane,strong,0.849389,2.048170,0.229811,0.670205,0.016160,0.234560,2.672096,5.0,0.749225,Yes,2.457654e-01,Yes,4.920009e-01,0.046991
23,N-Decane,strong,0.660662,0.056086,0.018181,0.724574,0.029734,0.011364,0.175909,No,3.413896,No,5.124052e-06,No,6.330778e-03,0.096211
24,N-Heptane,strong,0.793056,0.194206,0.032120,0.776969,0.022726,0.018464,0.282035,5.0,0.717200,No,1.985336e-02,Yes,4.773376e-01,0.047531
25,N-Hexane,strong,0.375077,2.727679,0.208920,0.197837,0.014622,0.550462,2.925728,No,2.995892,No,3.146464e-06,No,3.198408e-02,0.081498
26,N-Nonane,strong,0.593540,0.100968,0.019490,0.661976,0.031367,0.012031,0.179389,No,2.659328,No,3.265367e-05,No,2.519693e-02,0.083827
27,N-Octane,strong,0.599064,0.144393,0.025985,0.660512,0.030941,0.015930,0.236349,No,1.491957,No,1.102600e-02,Yes,1.005323e-01,0.069234
28,N-Pentane,strong,0.804623,1.572481,0.189237,0.658100,0.018569,0.177258,2.137345,No,1.966185,No,7.009372e-07,Yes,1.607312e-01,0.063526
29,N-Propylbenzene,strong,0.857198,-0.010415,0.006393,0.932183,0.021786,0.004423,0.076295,No,6.010975,No,1.316919e-08,No,1.120241e-03,0.109777
30,N-Undecane,strong,0.612729,0.094879,0.014874,0.603625,0.027478,0.011547,0.155987,No,2.657996,No,1.130283e-04,No,2.663652e-02,0.083290
31,O-Ethyltoluene,strong,0.795730,-0.010294,0.013712,0.891059,0.025851,0.008125,0.138397,1.0,0.919970,Yes,9.108928e-02,Yes,1.439253e-01,0.064915
32,O-Xylene,strong,0.834866,0.162413,0.032328,0.786857,0.020038,0.019601,0.293316,15.0,0.271781,Yes,3.986597e-01,Yes,8.834251e-01,0.032868
33,Propane,strong,0.608704,5.344521,0.454250,0.503722,0.023126,0.427186,4.724463,No,1.218019,No,1.963448e-02,Yes,2.695123e-01,0.056559
34,Propylene,strong,0.431606,1.488564,0.098476,0.252989,0.016624,0.199599,1.266881,15.0,0.299892,Yes,4.194547e-01,Yes,8.682599e-01,0.033548
35,Styrene,strong,0.374354,0.151516,0.024893,0.360670,0.026698,0.030365,0.313498,No,3.812835,No,9.080778e-08,No,3.142920e-02,0.081671
36,Toluene,strong,0.836969,1.135531,0.155054,0.749770,0.018948,0.101420,1.417391,15.0,0.269189,Yes,6.612023e-01,Yes,9.205326e-01,0.030998
37,Trans-2-Butene,strong,0.422533,0.073501,0.011369,0.303594,0.020322,0.022065,0.175550,No,19.784240,No,1.557602e-17,No,1.019618e-16,0.245042
38,Trans-2-Pentene,strong,0.763084,0.347060,0.037213,0.504441,0.016094,0.062694,0.541941,No,4.115818,No,3.937532e-07,No,1.897583e-02,0.086514
39,Unidentified,strong,0.026089,14.482927,1.031146,0.035142,0.012294,3.110433,11.838253,No,23.880908,No,1.199210e-22,No,3.054550e-10,0.190605
40,TNMOC,strong,0.825778,23.837493,4.979966,0.809791,0.021298,2.892040,45.115879,10.0,0.608468,Yes,5.889807e-02,Yes,6.692335e-01,0.040852

In [24]:
_ = model_analysis.plot_estimated_observed(feature_idx=0)

In [25]:
model_analysis.plot_estimated_timeseries(feature_idx=0)

In [26]:
model_analysis.plot_factor_profile(factor_idx=1)

In [27]:
model_analysis.plot_all_factors()

In [28]:
model_analysis.plot_all_factors_3d()

In [29]:
model_analysis.plot_factor_fingerprints()

In [30]:
model_analysis.plot_g_space(factor_1=2, factor_2=1)

In [31]:
model_analysis.plot_factor_contributions(feature_idx=1)

In [32]:
model_analysis.plot_factor_composition()

In [33]:
model_analysis.plot_factor_surface(factor_idx=None, feature_idx=1, percentage=True)

## Error Estimation — Displacement (GPU)

In [34]:
from esat.error.displacement import Displacement

In [35]:
disp = Displacement(sa=sa_model, feature_labels=data_handler.features,
                     model_selected=best_model, features=[0,1,2],
                     use_gpu=use_gpu, parallel=parallel)
print("DISP backend: %s" % ("gpu" if disp.use_gpu else "cpu"))

DISP backend: gpu

In [36]:
%%time
disp.run()

+ : Batch 1, Factor 1 - Features:   0%|          | 0/3 [00:00<?, ?it/s]

+ : Batch 1, Factor 1 - Features: 100%|██████████| 3/3 [00:00<00:00, 1556.14it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 2 - Features: 100%|██████████| 3/3 [00:00<00:00, 1853.97it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 3 - Features: 100%|██████████| 3/3 [00:00<00:00, 1716.16it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 4 - Features: 100%|██████████| 3/3 [00:00<00:00, 2080.51it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 5 - Features: 100%|██████████| 3/3 [00:00<00:00, 1930.78it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 6 - Features: 100%|██████████| 3/3 [00:00<00:00, 1830.51it/s]
[esat_rust] Metal device initialized successfully
Increasing value for factors: 100%|██████████| 6/6 [00:09<00:00,  1.55s/it]
- : Batch 1, Factor 1 - Features: 100%|██████████| 3/3 [00:00<00:00, 1434.60it/s]
[esat_rust] Metal device initialized successfully
- : Batch 1, Factor 2 - Features: 100%|██████████| 3/3 [00:00<00:00, 2001.42it/s]
[esat_rust] Metal device initialized successfully
- : Batch 1, Factor 3 - Features: 100%|██████████| 3/3 [00:00<00:00, 1393.46it/s]
[esat_rust] Metal device initialized successfully
- : Batch 1, Factor 4 - Features: 100%|██████████| 3/3 [00:00<00:00, 1183.38it/s]
[esat_rust] Metal device initialized successfully
- : Batch 1, Factor 5 - Features: 100%|██████████| 3/3 [00:00<00:00, 1219.63it/s]
Decreasing value for factors:  83%|████████▎ | 5/6 [00:07<00:01,  1.56s/it][esat_rust] Metal device initialized successfully
- : Batch 1, Factor 6 - Features: 100%|██████████| 3/3 [00:00<00:00, 1191.45it/s]
[esat_rust] Metal device initialized successfully
Decreasing value for factors: 100%|██████████| 6/6 [00:09<00:00,  1.56s/it]

CPU times: user 5.55 s, sys: 2.77 s, total: 8.31 s
Wall time: 18.7 s

In [37]:
disp.summary()

In [38]:
disp.plot_results(factor=3)

## Error Estimation — Bootstrap (GPU)

In [39]:
from esat.error.bootstrap import Bootstrap

In [40]:
model_selected = sa_models.best_model
nmf_model = sa_models.results[model_selected]
feature_labels = data_handler.features
bootstrap_n = 20
block_size = data_handler.optimal_block
threshold = 0.6
print("Optimal BS block size: %d" % data_handler.optimal_block)

Optimal BS block size: 4

In [41]:
bs = Bootstrap(sa=sa_model, feature_labels=feature_labels, model_selected=model_selected,
               bootstrap_n=bootstrap_n, block_size=block_size, threshold=threshold,
               seed=seed, use_gpu=use_gpu, parallel=parallel)

In [42]:
%%time
bs.run()

CPU times: user 499 ms, sys: 238 ms, total: 737 ms
Wall time: 2.03 s

[esat_rust] Metal device initialized successfully

In [43]:
bs.summary()

In [44]:
bs.q_results

       Q(robust)
0   53726.689088
1   50287.148232
2   54804.059133
3   53185.306735
4   53945.720392
5   52216.417524
6   54918.566843
7   54217.642196
8   54777.749419
9   54034.414776
10  49865.053465
11  53218.357850
12  54930.035511
13  52694.518914
14  52990.243612
15  54526.858169
16  55439.543546
17  55522.386739
18  53829.021241
19  51957.910324

In [45]:
# bs.plot_results(factor=1)

## Error Estimation — BS-DISP (GPU)

In [46]:
from esat.error.bs_disp import BSDISP

In [47]:
model_selected = sa_models.best_model
sa_model = sa_models.results[model_selected]
bootstrap_n = 10
block_size = data_handler.optimal_block
threshold = 0.6
threshold_dQ = 0.1
max_search = 50
features = [0, 1, 2]

In [48]:
bsdisp = BSDISP(sa=sa_model, feature_labels=feature_labels, model_selected=model_selected,
                  bootstrap_n=bootstrap_n, block_size=block_size, threshold=threshold,
                  max_search=max_search, threshold_dQ=threshold_dQ, features=features,
                  seed=seed, use_gpu=use_gpu)

In [49]:
%%capture
bsdisp.run(parallel=parallel)

[esat_rust] Metal device initialized successfully

/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: divide by zero encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: overflow encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/model/sa.py:467: RuntimeWarning: invalid value encountered in matmul
  self.WH = np.matmul(self.W, self.H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: overflow encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:15: RuntimeWarning: invalid value encountered in matmul
  _wh = np.matmul(W, H)
/Users/joallee/Project/esat-gpu-study/esat/metrics.py:27: RuntimeWarning: divide by zero encountered in matmul
  _wh = np.matmul(W, H)

In [50]:
bsdisp.summary()

In [51]:
bsdisp.plot_results(factor=1)

### Combined Error Plot

In [52]:
from esat.error.error import Error

In [53]:
error = Error(bs=bs, disp=disp, bsdisp=bsdisp)

In [54]:
error.plot_summary(factor=1)

## Constrained Model

In [55]:
from esat.rotational.constrained import ConstrainedModel
cm = ConstrainedModel(base_model=sa_model, data_handler=data_handler, softness=1.0)

In [56]:
cm.add_constraint(constraint_type="define limits", index=(2,10), target="feature", min_value=0.1, max_value=0.9)

True

In [57]:
cm.list_constraints()

In [60]:
cm.remove_constraint(constraint_label="factor:0|feature:3")

KeyError: 'factor:0|feature:3'

In [61]:
expression1 = "(0.66*[factor:1|feature:2])-(4.2*[factor:2|feature:4])=0,250"
expression2 = "(0.35*[factor:0|feature:3])-(2.0*[factor:1|feature:3])-(3.7*[factor:3|feature:4])=0,250"
cm.add_expression(expression1)
cm.add_expression(expression2)

True

In [62]:
cm.list_expressions()

In [63]:
cm.train(max_iterations=20000)

Q(Robust): 58001.516, Q(Main): 68941.067, Q(aux): 559.86, dQ: 0.0121:   2%|▏         | 421/20000 [00:02<02:00, 162.48it/s]

In [64]:
cm.display_results()
cm.plot_Q(Qtype="Aux")

In [65]:
cm.evaluate_constraints()

In [66]:
cm.evaluate_expressions()

In [67]:
cm.plot_profile_contributions(factor_idx=1)

In [68]:
cm.plot_factor_fingerprints()

In [69]:
cm.plot_g_space(factor_idx1=1, factor_idx2=2, show_base=True, show_delta=True)

In [70]:
cm.plot_factor_contributions(feature_idx=4)

In [71]:
cm_model = cm.constrained_model

## Error Estimation on Constrained Model (GPU)

In [72]:
cm_disp = Displacement(sa=cm_model, feature_labels=data_handler.features,
                          model_selected="constrained", features=[0,1,2,3,4],
                          use_gpu=use_gpu, parallel=parallel)

In [73]:
%%time
cm_disp.run()

+ : Batch 1, Factor 1 - Features: 100%|██████████| 5/5 [00:00<00:00, 2104.31it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 2 - Features: 100%|██████████| 5/5 [00:00<00:00, 2341.88it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 3 - Features: 100%|██████████| 5/5 [00:00<00:00, 2117.69it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 4 - Features: 100%|██████████| 5/5 [00:00<00:00, 2232.20it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 5 - Features: 100%|██████████| 5/5 [00:00<00:00, 2281.99it/s]
[esat_rust] Metal device initialized successfully
+ : Batch 1, Factor 6 - Features: 100%|██████████| 5/5 [00:00<00:00, 1790.30it/s]
[esat_rust] Metal device initialized successfully
Increasing value for factors: 100%|██████████| 6/6 [00:12<00:00,  2.03s/it]
- : Batch 1, Factor 1 - Features: 100%|██████████| 5/5 [00:00<00:00, 587.98it/s]
Decreasing value for factors:  17%|█▋        | 1/6 [00:02<00:10,  2.12s/it][esat_rust] Metal device initialized successfully
- : Batch 1, Factor 2 - Features: 100%|██████████| 5/5 [00:00<00:00, 1603.08it/s]
Decreasing value for factors:  33%|███▎      | 2/6 [00:04<00:08,  2.10s/it][esat_rust] Metal device initialized successfully
- : Batch 1, Factor 3 - Features: 100%|██████████| 5/5 [00:00<00:00, 1583.83it/s]
Decreasing value for factors:  50%|█████     | 3/6 [00:06<00:06,  2.09s/it][esat_rust] Metal device initialized successfully
- : Batch 1, Factor 4 - Features: 100%|██████████| 5/5 [00:00<00:00, 1533.23it/s]
[esat_rust] Metal device initialized successfully
- : Batch 1, Factor 5 - Features: 100%|██████████| 5/5 [00:00<00:00, 1458.48it/s]
[esat_rust] Metal device initialized successfully
- : Batch 1, Factor 6 - Features: 100%|██████████| 5/5 [00:00<00:00, 1725.91it/s]
Decreasing value for factors: 100%|██████████| 6/6 [00:12<00:00,  2.03s/it][esat_rust] Metal device initialized successfully
Decreasing value for factors: 100%|██████████| 6/6 [00:12<00:00,  2.05s/it]

CPU times: user 5.67 s, sys: 2.83 s, total: 8.5 s
Wall time: 24.4 s

In [74]:
cm_disp.summary()

In [75]:
cm_disp.plot_results(factor=1)

In [76]:
cm_bs = Bootstrap(sa=cm_model, feature_labels=feature_labels, model_selected="constrained",
                   bootstrap_n=20, block_size=data_handler.optimal_block, threshold=0.6,
                   seed=seed, use_gpu=use_gpu, parallel=parallel)

In [77]:
%%time
cm_bs.run()

CPU times: user 494 ms, sys: 234 ms, total: 729 ms
Wall time: 2.07 s

[esat_rust] Metal device initialized successfully

In [78]:
cm_bs.summary()

In [79]:
cm_bs.plot_results(factor=1)